name = "access-youtube"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".open-next/assets"
pages_builds = [
  { command = "npx @opennextjs/cloudflare build", cwd = "." }
]

[assets]
directory = ".open-next/assets"

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
