name = "access-youtube"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
